/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ListaDesideriRouteImport } from './routes/lista-desideri'
import { Route as SerieIndexRouteImport } from './routes/serie/index'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as SerieId_and_titleRouteImport } from './routes/serie/$id_and_title'
import { Route as FilmId_and_titleRouteImport } from './routes/film/$id_and_title'
import { Route as AccountRegisterRouteImport } from './routes/account/register'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountLoginRouteImport } from './routes/account/login'
import { Route as FilmSearchIndexRouteImport } from './routes/film/search/index'
import { Route as SerieGenresGenres_and_idRouteImport } from './routes/serie/genres/$genres_and_id'
import { Route as FilmGenresGenres_and_idRouteImport } from './routes/film/genres/$genres_and_id'

const ListaDesideriRoute = ListaDesideriRouteImport.update({
  id: '/lista-desideri',
  path: '/lista-desideri',
  getParentRoute: () => rootRouteImport,
} as any)
const SerieIndexRoute = SerieIndexRouteImport.update({
  id: '/serie/',
  path: '/serie/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SerieId_and_titleRoute = SerieId_and_titleRouteImport.update({
  id: '/serie/$id_and_title',
  path: '/serie/$id_and_title',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmId_and_titleRoute = FilmId_and_titleRouteImport.update({
  id: '/film/$id_and_title',
  path: '/film/$id_and_title',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/account/register',
  path: '/account/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmSearchIndexRoute = FilmSearchIndexRouteImport.update({
  id: '/film/search/',
  path: '/film/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const SerieGenresGenres_and_idRoute =
  SerieGenresGenres_and_idRouteImport.update({
    id: '/serie/genres/$genres_and_id',
    path: '/serie/genres/$genres_and_id',
    getParentRoute: () => rootRouteImport,
  } as any)
const FilmGenresGenres_and_idRoute = FilmGenresGenres_and_idRouteImport.update({
  id: '/film/genres/$genres_and_id',
  path: '/film/genres/$genres_and_id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/lista-desideri': typeof ListaDesideriRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/register': typeof AccountRegisterRoute
  '/film/$id_and_title': typeof FilmId_and_titleRoute
  '/serie/$id_and_title': typeof SerieId_and_titleRoute
  '/': typeof homeIndexRoute
  '/serie': typeof SerieIndexRoute
  '/film/genres/$genres_and_id': typeof FilmGenresGenres_and_idRoute
  '/serie/genres/$genres_and_id': typeof SerieGenresGenres_and_idRoute
  '/film/search': typeof FilmSearchIndexRoute
}
export interface FileRoutesByTo {
  '/lista-desideri': typeof ListaDesideriRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/register': typeof AccountRegisterRoute
  '/film/$id_and_title': typeof FilmId_and_titleRoute
  '/serie/$id_and_title': typeof SerieId_and_titleRoute
  '/': typeof homeIndexRoute
  '/serie': typeof SerieIndexRoute
  '/film/genres/$genres_and_id': typeof FilmGenresGenres_and_idRoute
  '/serie/genres/$genres_and_id': typeof SerieGenresGenres_and_idRoute
  '/film/search': typeof FilmSearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/lista-desideri': typeof ListaDesideriRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/register': typeof AccountRegisterRoute
  '/film/$id_and_title': typeof FilmId_and_titleRoute
  '/serie/$id_and_title': typeof SerieId_and_titleRoute
  '/(home)/': typeof homeIndexRoute
  '/serie/': typeof SerieIndexRoute
  '/film/genres/$genres_and_id': typeof FilmGenresGenres_and_idRoute
  '/serie/genres/$genres_and_id': typeof SerieGenresGenres_and_idRoute
  '/film/search/': typeof FilmSearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/lista-desideri'
    | '/account/login'
    | '/account/profile'
    | '/account/register'
    | '/film/$id_and_title'
    | '/serie/$id_and_title'
    | '/'
    | '/serie'
    | '/film/genres/$genres_and_id'
    | '/serie/genres/$genres_and_id'
    | '/film/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/lista-desideri'
    | '/account/login'
    | '/account/profile'
    | '/account/register'
    | '/film/$id_and_title'
    | '/serie/$id_and_title'
    | '/'
    | '/serie'
    | '/film/genres/$genres_and_id'
    | '/serie/genres/$genres_and_id'
    | '/film/search'
  id:
    | '__root__'
    | '/lista-desideri'
    | '/account/login'
    | '/account/profile'
    | '/account/register'
    | '/film/$id_and_title'
    | '/serie/$id_and_title'
    | '/(home)/'
    | '/serie/'
    | '/film/genres/$genres_and_id'
    | '/serie/genres/$genres_and_id'
    | '/film/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ListaDesideriRoute: typeof ListaDesideriRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  FilmId_and_titleRoute: typeof FilmId_and_titleRoute
  SerieId_and_titleRoute: typeof SerieId_and_titleRoute
  homeIndexRoute: typeof homeIndexRoute
  SerieIndexRoute: typeof SerieIndexRoute
  FilmGenresGenres_and_idRoute: typeof FilmGenresGenres_and_idRoute
  SerieGenresGenres_and_idRoute: typeof SerieGenresGenres_and_idRoute
  FilmSearchIndexRoute: typeof FilmSearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lista-desideri': {
      id: '/lista-desideri'
      path: '/lista-desideri'
      fullPath: '/lista-desideri'
      preLoaderRoute: typeof ListaDesideriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serie/': {
      id: '/serie/'
      path: '/serie'
      fullPath: '/serie'
      preLoaderRoute: typeof SerieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serie/$id_and_title': {
      id: '/serie/$id_and_title'
      path: '/serie/$id_and_title'
      fullPath: '/serie/$id_and_title'
      preLoaderRoute: typeof SerieId_and_titleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/$id_and_title': {
      id: '/film/$id_and_title'
      path: '/film/$id_and_title'
      fullPath: '/film/$id_and_title'
      preLoaderRoute: typeof FilmId_and_titleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/register': {
      id: '/account/register'
      path: '/account/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/search/': {
      id: '/film/search/'
      path: '/film/search'
      fullPath: '/film/search'
      preLoaderRoute: typeof FilmSearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serie/genres/$genres_and_id': {
      id: '/serie/genres/$genres_and_id'
      path: '/serie/genres/$genres_and_id'
      fullPath: '/serie/genres/$genres_and_id'
      preLoaderRoute: typeof SerieGenresGenres_and_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/genres/$genres_and_id': {
      id: '/film/genres/$genres_and_id'
      path: '/film/genres/$genres_and_id'
      fullPath: '/film/genres/$genres_and_id'
      preLoaderRoute: typeof FilmGenresGenres_and_idRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ListaDesideriRoute: ListaDesideriRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  FilmId_and_titleRoute: FilmId_and_titleRoute,
  SerieId_and_titleRoute: SerieId_and_titleRoute,
  homeIndexRoute: homeIndexRoute,
  SerieIndexRoute: SerieIndexRoute,
  FilmGenresGenres_and_idRoute: FilmGenresGenres_and_idRoute,
  SerieGenresGenres_and_idRoute: SerieGenresGenres_and_idRoute,
  FilmSearchIndexRoute: FilmSearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
