/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as FilmId_and_titleRouteImport } from './routes/film/$id_and_title'
import { Route as FilmSearchIndexRouteImport } from './routes/film/search/index'
import { Route as FilmGenresGenres_and_idRouteImport } from './routes/film/genres/$genres_and_id'

const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmId_and_titleRoute = FilmId_and_titleRouteImport.update({
  id: '/film/$id_and_title',
  path: '/film/$id_and_title',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmSearchIndexRoute = FilmSearchIndexRouteImport.update({
  id: '/film/search/',
  path: '/film/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmGenresGenres_and_idRoute = FilmGenresGenres_and_idRouteImport.update({
  id: '/film/genres/$genres_and_id',
  path: '/film/genres/$genres_and_id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/film/$id_and_title': typeof FilmId_and_titleRoute
  '/': typeof homeIndexRoute
  '/film/genres/$genres_and_id': typeof FilmGenresGenres_and_idRoute
  '/film/search': typeof FilmSearchIndexRoute
}
export interface FileRoutesByTo {
  '/film/$id_and_title': typeof FilmId_and_titleRoute
  '/': typeof homeIndexRoute
  '/film/genres/$genres_and_id': typeof FilmGenresGenres_and_idRoute
  '/film/search': typeof FilmSearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/film/$id_and_title': typeof FilmId_and_titleRoute
  '/(home)/': typeof homeIndexRoute
  '/film/genres/$genres_and_id': typeof FilmGenresGenres_and_idRoute
  '/film/search/': typeof FilmSearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/film/$id_and_title'
    | '/'
    | '/film/genres/$genres_and_id'
    | '/film/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/film/$id_and_title'
    | '/'
    | '/film/genres/$genres_and_id'
    | '/film/search'
  id:
    | '__root__'
    | '/film/$id_and_title'
    | '/(home)/'
    | '/film/genres/$genres_and_id'
    | '/film/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FilmId_and_titleRoute: typeof FilmId_and_titleRoute
  homeIndexRoute: typeof homeIndexRoute
  FilmGenresGenres_and_idRoute: typeof FilmGenresGenres_and_idRoute
  FilmSearchIndexRoute: typeof FilmSearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/$id_and_title': {
      id: '/film/$id_and_title'
      path: '/film/$id_and_title'
      fullPath: '/film/$id_and_title'
      preLoaderRoute: typeof FilmId_and_titleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/search/': {
      id: '/film/search/'
      path: '/film/search'
      fullPath: '/film/search'
      preLoaderRoute: typeof FilmSearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/genres/$genres_and_id': {
      id: '/film/genres/$genres_and_id'
      path: '/film/genres/$genres_and_id'
      fullPath: '/film/genres/$genres_and_id'
      preLoaderRoute: typeof FilmGenresGenres_and_idRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  FilmId_and_titleRoute: FilmId_and_titleRoute,
  homeIndexRoute: homeIndexRoute,
  FilmGenresGenres_and_idRoute: FilmGenresGenres_and_idRoute,
  FilmSearchIndexRoute: FilmSearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
